{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import time\n",
    "import heapq  \n",
    "\n",
    "def in_mt(mt):\n",
    "    res = \"\"\n",
    "    for i in range(3):\n",
    "        row = \"\"\n",
    "        for j in range(3):\n",
    "            val = mt[i*3 + j]\n",
    "            if val == 0:\n",
    "                row += \" [ ] \"\n",
    "            else:\n",
    "                row += f\"  {val}  \"\n",
    "        res += row + \"\\n\"\n",
    "    res += \"-\" * 20 + \"\\n\"\n",
    "    return res\n",
    "\n",
    "def get_successors(mt):\n",
    "    pos = mt.index(0)\n",
    "    r, c = pos // 3, pos % 3\n",
    "    successors = []\n",
    "    \n",
    "    def swap(mt, i, j):\n",
    "        new_mt = list(mt)\n",
    "        new_mt[i], new_mt[j] = new_mt[j], new_mt[i]\n",
    "        return new_mt\n",
    "        \n",
    "    if r > 0: \n",
    "        new_state = swap(mt, pos, pos - 3)\n",
    "        successors.append((\"Lên\", new_state))\n",
    "    if r < 2: \n",
    "        new_state = swap(mt, pos, pos + 3)\n",
    "        successors.append((\"Xuống\", new_state))\n",
    "    if c > 0: \n",
    "        new_state = swap(mt, pos, pos - 1)\n",
    "        successors.append((\"Trái\", new_state))\n",
    "    if c < 2: \n",
    "        new_state = swap(mt, pos, pos + 1)\n",
    "        successors.append((\"Phải\", new_state))\n",
    "    return successors\n",
    "\n",
    "def manhattan_distance(state, goal_state):\n",
    "    distance = 0\n",
    "    for i in range(1, 9):\n",
    "        if i in state and i in goal_state:\n",
    "            pos_state = state.index(i)\n",
    "            pos_goal = goal_state.index(i)\n",
    "            r_s, c_s = pos_state // 3, pos_state % 3\n",
    "            r_g, c_g = pos_goal // 3, pos_goal % 3\n",
    "            distance += abs(r_s - r_g) + abs(c_s - c_g)\n",
    "    return distance\n",
    "\n",
    "def greedy_manhattan_solve(start_state, goal_state):\n",
    "    \"\"\"Greedy Best-First Search: f(n) = h(n) (chỉ dùng heuristic Manhattan)\"\"\"\n",
    "    if start_state == goal_state:\n",
    "        return [], 0\n",
    "        \n",
    "    # Frontier lưu trữ dưới dạng Min-Heap:\n",
    "    # Mỗi phần tử là tuple: (h, counter, node_hiện_tại, đường_đi)\n",
    "\n",
    "    counter = 0\n",
    "    frontier = []\n",
    "    h_start = manhattan_distance(start_state, goal_state)\n",
    "    heapq.heappush(frontier, (h_start, counter, start_state, []))\n",
    "    \n",
    "    # Tập Reached: lưu các trạng thái đã được thêm vào Frontier để tránh lặp\n",
    "    reached = {tuple(start_state)}\n",
    "    nodes_generated = 1\n",
    "    \n",
    "    while frontier:\n",
    "        # Lấy trạng thái có h(n) nhỏ nhất ra duyệt\n",
    "        h, _, node, path = heapq.heappop(frontier)\n",
    "        \n",
    "        # Kiểm tra đích khi lấy ra khỏi Frontier (Late goal test)\n",
    "        if node == goal_state:\n",
    "            return path, nodes_generated\n",
    "            \n",
    "        for action, child in get_successors(node):\n",
    "            child_tuple = tuple(child)\n",
    "            \n",
    "            # Chỉ nạp vào Frontier nếu trạng thái chưa từng xuất hiện trong Reached\n",
    "            if child_tuple not in reached:\n",
    "                reached.add(child_tuple)\n",
    "                nodes_generated += 1\n",
    "                counter += 1\n",
    "                h_child = manhattan_distance(child, goal_state)\n",
    "                heapq.heappush(frontier, (h_child, counter, child, path + [(action, child)]))\n",
    "                    \n",
    "    return None, nodes_generated"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
