{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import time\n",
    "\n",
    "def in_mt(mt):\n",
    "    res = \"\"\n",
    "    for i in range(3):\n",
    "        row = \"\"\n",
    "        for j in range(3):\n",
    "            val = mt[i*3 + j]\n",
    "            if val == 0:\n",
    "                row += \" [ ] \"\n",
    "            else:\n",
    "                row += f\"  {val}  \"\n",
    "        res += row + \"\\n\"\n",
    "    res += \"-\" * 20 + \"\\n\"\n",
    "    return res\n",
    "\n",
    "def get_successors(mt):\n",
    "    pos = mt.index(0)\n",
    "    r, c = pos // 3, pos % 3\n",
    "    successors = []\n",
    "    \n",
    "    def swap(mt, i, j):\n",
    "        new_mt = list(mt)\n",
    "        new_mt[i], new_mt[j] = new_mt[j], new_mt[i]\n",
    "        return new_mt\n",
    "        \n",
    "    if r > 0: \n",
    "        new_state = swap(mt, pos, pos - 3)\n",
    "        successors.append((\"Lên\", new_state))\n",
    "    if r < 2: \n",
    "        new_state = swap(mt, pos, pos + 3)\n",
    "        successors.append((\"Xuống\", new_state))\n",
    "    if c > 0: \n",
    "        new_state = swap(mt, pos, pos - 1)\n",
    "        successors.append((\"Trái\", new_state))\n",
    "    if c < 2: \n",
    "        new_state = swap(mt, pos, pos + 1)\n",
    "        successors.append((\"Phải\", new_state))\n",
    "    return successors\n",
    "\n",
    "def manhattan_distance(state, goal_state):\n",
    "    distance = 0\n",
    "    for i in range(1, 9):\n",
    "        if i in state and i in goal_state:\n",
    "            pos_state = state.index(i)\n",
    "            pos_goal = goal_state.index(i)\n",
    "            r_s, c_s = pos_state // 3, pos_state % 3\n",
    "            r_g, c_g = pos_goal // 3, pos_goal % 3\n",
    "            distance += abs(r_s - r_g) + abs(c_s - c_g)\n",
    "    return distance\n",
    "\n",
    "def count_misplaced(state, goal_state):\n",
    "    count = 0\n",
    "    for i in range(9):\n",
    "        if state[i] != 0 and state[i] != goal_state[i]:\n",
    "            count += 1\n",
    "    return count\n",
    "\n",
    "def ida_star_solve(start_state, goal_state):\n",
    "    \"\"\"Iterative Deepening A* (IDA*) using misplaced tiles as heuristic\"\"\"\n",
    "    if start_state == goal_state:\n",
    "        return [], 0\n",
    "        \n",
    "    def search(path, path_set, g, f_limit):\n",
    "        nonlocal nodes_generated\n",
    "        nodes_generated += 1\n",
    "        \n",
    "        current_state = path[-1][1] if path else start_state\n",
    "        h = count_misplaced(current_state, goal_state)\n",
    "        f = g + h\n",
    "        \n",
    "        if f > f_limit:\n",
    "            return f, None\n",
    "            \n",
    "        if current_state == goal_state:\n",
    "            return \"FOUND\", path\n",
    "            \n",
    "        min_limit = float('inf')\n",
    "        \n",
    "        for action, neighbor in get_successors(current_state):\n",
    "            neighbor_tuple = tuple(neighbor)\n",
    "            if neighbor_tuple not in path_set:\n",
    "                path.append((action, neighbor))\n",
    "                path_set.add(neighbor_tuple)\n",
    "                \n",
    "                res, found_path = search(path, path_set, g + 1, f_limit)\n",
    "                if res == \"FOUND\":\n",
    "                    return \"FOUND\", found_path\n",
    "                if res < min_limit:\n",
    "                    min_limit = res\n",
    "                    \n",
    "                path_set.remove(neighbor_tuple)\n",
    "                path.pop()\n",
    "                \n",
    "        return min_limit, None\n",
    "\n",
    "    f_limit = count_misplaced(start_state, goal_state)\n",
    "    path = []\n",
    "    path_set = {tuple(start_state)}\n",
    "    total_nodes_generated = 0\n",
    "    \n",
    "    while True:\n",
    "        nodes_generated = 0\n",
    "        res, found_path = search(path, path_set, 0, f_limit)\n",
    "        total_nodes_generated += nodes_generated\n",
    "        if res == \"FOUND\":\n",
    "            return found_path, total_nodes_generated\n",
    "        if res == float('inf'):\n",
    "            return None, total_nodes_generated\n",
    "        f_limit = res"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "nbformat_minor": 0,
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
